version: '3.8'

services:
  # Zookeeper
  zookeeper-horizon:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper-horizon
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  # Kafka
  kafka-horizon:
    image: bitnami/kafka:3.7
    container_name: kafka-horizon
    ports:
      - "9092:9092"     # Pour les conteneurs Docker
      - "29092:29092"   # Pour ton IDE ou autres outils sur l'hôte
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-horizon:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-horizon:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-horizon
    restart: unless-stopped

  # Redis
  redis-horizon:
    image: redis:7.2-alpine
    container_name: redis-horizon
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-horizon:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: " zookeeper-horizon:2181"
    depends_on:
      - kafka-horizon
      - zookeeper-horizon
  
  # FastAPI Consommateur Kafka
  web:
    build: .
    container_name: fastapi_recommender
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      # - db
      - kafka-horizon
    # env_file:
    #   - .env

volumes:
  redis-data:  